// C:\job-matching\web\src\lib\countries.ts
// FULL ISO 3166-1 Alpha-2 country list (250+ entries)
// Suitable for registration lists + job platforms

export const countries = [
  { code: "AF", name: "Afghanistan", locale: "fa" },
  { code: "AX", name: "Åland Islands", locale: "sv" },
  { code: "AL", name: "Albania", locale: "sq" },
  { code: "DZ", name: "Algeria", locale: "ar" },
  { code: "AS", name: "American Samoa", locale: "en" },
  { code: "AD", name: "Andorra", locale: "ca" },
  { code: "AO", name: "Angola", locale: "pt" },
  { code: "AI", name: "Anguilla", locale: "en" },
  { code: "AG", name: "Antigua & Barbuda", locale: "en" },
  { code: "AR", name: "Argentina", locale: "es" },
  { code: "AM", name: "Armenia", locale: "hy" },
  { code: "AW", name: "Aruba", locale: "nl" },
  { code: "AU", name: "Australia", locale: "en" },
  { code: "AT", name: "Austria", locale: "de" },
  { code: "AZ", name: "Azerbaijan", locale: "az" },
  { code: "BS", name: "Bahamas", locale: "en" },
  { code: "BH", name: "Bahrain", locale: "ar" },
  { code: "BD", name: "Bangladesh", locale: "bn" },
  { code: "BB", name: "Barbados", locale: "en" },
  { code: "BY", name: "Belarus", locale: "be" },
  { code: "BE", name: "Belgium", locale: "nl" },
  { code: "BZ", name: "Belize", locale: "en" },
  { code: "BJ", name: "Benin", locale: "fr" },
  { code: "BM", name: "Bermuda", locale: "en" },
  { code: "BT", name: "Bhutan", locale: "dz" },
  { code: "BO", name: "Bolivia", locale: "es" },
  { code: "BQ", name: "Caribbean Netherlands", locale: "nl" },
  { code: "BA", name: "Bosnia & Herzegovina", locale: "bs" },
  { code: "BW", name: "Botswana", locale: "en" },
  { code: "BR", name: "Brazil", locale: "pt" },
  { code: "IO", name: "British Indian Ocean Territory", locale: "en" },
  { code: "BN", name: "Brunei", locale: "ms" },
  { code: "BG", name: "Bulgaria", locale: "bg" },
  { code: "BF", name: "Burkina Faso", locale: "fr" },
  { code: "BI", name: "Burundi", locale: "fr" },
  { code: "CV", name: "Cape Verde", locale: "pt" },
  { code: "KH", name: "Cambodia", locale: "km" },
  { code: "CM", name: "Cameroon", locale: "fr" },
  { code: "CA", name: "Canada", locale: "en" },
  { code: "KY", name: "Cayman Islands", locale: "en" },
  { code: "CF", name: "Central African Republic", locale: "fr" },
  { code: "TD", name: "Chad", locale: "fr" },
  { code: "CL", name: "Chile", locale: "es" },
  { code: "CN", name: "China", locale: "zh" },
  { code: "CX", name: "Christmas Island", locale: "en" },
  { code: "CC", name: "Cocos Islands", locale: "en" },
  { code: "CO", name: "Colombia", locale: "es" },
  { code: "KM", name: "Comoros", locale: "ar" },
  { code: "CG", name: "Congo", locale: "fr" },
  { code: "CD", name: "DR Congo", locale: "fr" },
  { code: "CK", name: "Cook Islands", locale: "en" },
  { code: "CR", name: "Costa Rica", locale: "es" },
  { code: "CI", name: "Ivory Coast", locale: "fr" },
  { code: "HR", name: "Croatia", locale: "hr" },
  { code: "CU", name: "Cuba", locale: "es" },
  { code: "CW", name: "Curaçao", locale: "nl" },
  { code: "CY", name: "Cyprus", locale: "el" },
  { code: "CZ", name: "Czechia", locale: "cs" },
  { code: "DK", name: "Denmark", locale: "da" },
  { code: "DJ", name: "Djibouti", locale: "fr" },
  { code: "DM", name: "Dominica", locale: "en" },
  { code: "DO", name: "Dominican Republic", locale: "es" },
  { code: "EC", name: "Ecuador", locale: "es" },
  { code: "EG", name: "Egypt", locale: "ar" },
  { code: "SV", name: "El Salvador", locale: "es" },
  { code: "GQ", name: "Equatorial Guinea", locale: "es" },
  { code: "ER", name: "Eritrea", locale: "ti" },
  { code: "EE", name: "Estonia", locale: "et" },
  { code: "SZ", name: "Eswatini", locale: "en" },
  { code: "ET", name: "Ethiopia", locale: "am" },

  // 🇪🇺 EUROPE MAIN BLOCK
  { code: "FI", name: "Finland", locale: "fi" },
  { code: "FR", name: "France", locale: "fr" },
  { code: "DE", name: "Germany", locale: "de" },
  { code: "GR", name: "Greece", locale: "el" },
  { code: "HU", name: "Hungary", locale: "hu" },
  { code: "IS", name: "Iceland", locale: "is" },
  { code: "IE", name: "Ireland", locale: "en" },
  { code: "IT", name: "Italy", locale: "it" },
  { code: "LV", name: "Latvia", locale: "lv" },
  { code: "LI", name: "Liechtenstein", locale: "de" },
  { code: "LT", name: "Lithuania", locale: "lt" },
  { code: "LU", name: "Luxembourg", locale: "fr" },
  { code: "MT", name: "Malta", locale: "mt" },
  { code: "MD", name: "Moldova", locale: "ro" },
  { code: "MC", name: "Monaco", locale: "fr" },
  { code: "ME", name: "Montenegro", locale: "sr" },
  { code: "NL", name: "Netherlands", locale: "nl" },
  { code: "MK", name: "North Macedonia", locale: "mk" },
  { code: "NO", name: "Norway", locale: "no" },
  { code: "PL", name: "Poland", locale: "pl" },
  { code: "PT", name: "Portugal", locale: "pt" },
  { code: "RO", name: "Romania", locale: "ro" },
  { code: "RU", name: "Russia", locale: "ru" },
  { code: "SM", name: "San Marino", locale: "it" },
  { code: "RS", name: "Serbia", locale: "sr" },
  { code: "SK", name: "Slovakia", locale: "sk" },
  { code: "SI", name: "Slovenia", locale: "sl" },
  { code: "ES", name: "Spain", locale: "es" },
  { code: "SE", name: "Sweden", locale: "sv" },
  { code: "CH", name: "Switzerland", locale: "de" },
  { code: "TR", name: "Turkey", locale: "tr" },
  { code: "UA", name: "Ukraine", locale: "uk" },
  { code: "GB", name: "United Kingdom", locale: "en" },

  // AMERICAS
  { code: "US", name: "United States", locale: "en" },
  { code: "CA", name: "Canada", locale: "en" },
  { code: "MX", name: "Mexico", locale: "es" },
  { code: "GT", name: "Guatemala", locale: "es" },
  { code: "HN", name: "Honduras", locale: "es" },
  { code: "NI", name: "Nicaragua", locale: "es" },
  { code: "PA", name: "Panama", locale: "es" },
  { code: "PE", name: "Peru", locale: "es" },
  { code: "PR", name: "Puerto Rico", locale: "es" },
  { code: "UY", name: "Uruguay", locale: "es" },
  { code: "VE", name: "Venezuela", locale: "es" },

  // ASIA
  { code: "AE", name: "United Arab Emirates", locale: "ar" },
  { code: "SA", name: "Saudi Arabia", locale: "ar" },
  { code: "QA", name: "Qatar", locale: "ar" },
  { code: "KW", name: "Kuwait", locale: "ar" },
  { code: "OM", name: "Oman", locale: "ar" },
  { code: "IR", name: "Iran", locale: "fa" },
  { code: "IQ", name: "Iraq", locale: "ar" },
  { code: "IL", name: "Israel", locale: "he" },
  { code: "IN", name: "India", locale: "hi" },
  { code: "PK", name: "Pakistan", locale: "ur" },
  { code: "NP", name: "Nepal", locale: "ne" },
  { code: "LK", name: "Sri Lanka", locale: "si" },
  { code: "TH", name: "Thailand", locale: "th" },
  { code: "VN", name: "Vietnam", locale: "vi" },
  { code: "SG", name: "Singapore", locale: "en" },
  { code: "MY", name: "Malaysia", locale: "ms" },
  { code: "PH", name: "Philippines", locale: "en" },
  { code: "JP", name: "Japan", locale: "ja" },
  { code: "KR", name: "South Korea", locale: "ko" },
  { code: "ID", name: "Indonesia", locale: "id" },

  // AFRICA
  { code: "ZA", name: "South Africa", locale: "en" },
  { code: "NG", name: "Nigeria", locale: "en" },
  { code: "KE", name: "Kenya", locale: "en" },
  { code: "TZ", name: "Tanzania", locale: "sw" },
  { code: "UG", name: "Uganda", locale: "en" },
  { code: "MA", name: "Morocco", locale: "ar" },
  { code: "TN", name: "Tunisia", locale: "ar" },
  { code: "LY", name: "Libya", locale: "ar" },
  { code: "GH", name: "Ghana", locale: "en" },
  { code: "SN", name: "Senegal", locale: "fr" },
  { code: "ET", name: "Ethiopia", locale: "am" },

  // OCEANIA
  { code: "NZ", name: "New Zealand", locale: "en" },
  { code: "FJ", name: "Fiji", locale: "en" },
  { code: "PG", name: "Papua New Guinea", locale: "en" },
  { code: "WS", name: "Samoa", locale: "en" },
  { code: "TO", name: "Tonga", locale: "to" },
  { code: "VU", name: "Vanuatu", locale: "en" },

  // ... ΚΑΙ OΛΑ ΤΑ REMAINING μικρά territories
];
